service: box-skill-service

provider:
  name: google
  runtime: nodejs
  project: box-skill
  credentials: ~/.gcloud/keyfile.json

plugins:
  - serverless-google-cloudfunctions
  - serverless-offline

functions:
  first:
    handler: http
    events:
      - http: path
  second:
    handler: search
    events:
      - event:
        eventType: providers/cloud.pubsub/eventTypes/topic.publish
        resource: projects/*/topics/metadata
