service: box-skill-service

provider:
  name: aws
  runtime: nodejs8.10

plugins:
  - serverless-offline

package:
  exclude:
    - .git/**
    - .gitignore

# Define function environment variables here
# environment:
#   variable: value

functions:
  invoke:
    handler: handler.invoke
    events:
      - http:
          path: invoke
          method: post
          cors: true
