service: box-skill-service

provider:
  name: aws
  runtime: nodejs8.10

plugins:
  - serverless-offline

package:
  exclude:
    - .git/**
    - .gitignore

# Define function environment variables here
# environment:
#   variable2: value2

functions:
  http:
    handler: handler.http
    events:
      - http:
          path: http
          method: get
  invoke:
    handler: handler.invoke
    events:
      - http:
          path: boxskill
          method: post
          cors: true
