service: boxSkillService

provider:
  name: google
  runtime: nodejs
  project: box-skill
  credentials: ~/.gcloud/keyfile.json

functions:
  boxSkillFunction:
    handler: handler.boxSkillFunction
    events:
      - http:
          path: boxskill
          method: post
          cors: true

plugins:
  - serverless-offline
