service: boxSkillService

provider:
  name: aws
  runtime: nodejs8.10

functions:
  boxSkillFunction:
    handler: handler.boxSkillFunction
    events:
      - http:
          path: boxskill
          method: post
          cors: true

plugins:
  - serverless-offline
